version: '{build}'

skip_commits:
  files:
    - '**/*.md'

image: Visual Studio 2017

platform:
  - Win32
  - x64

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

environment:
  GLOBAL_VAR: v1.1.0
  VAR_B: value_a
  matrix:
    - VAR_A: value_a
    - VAR_A: value_b

configuration: Release

build_script:
  - cmd: |-
      echo %GLOBAL_VAR%
      echo %VAR_A%
      echo %VAR_B%

for:
  -
    matrix:
      only:
        - platform: Win32
        - VAR_A: value_a
      
    environment:
      VAR_B: value_b

  -
    matrix:
      only:
        - platform: x64
        - VAR_A: value_a

    environment:
      VAR_B: value_c