version: '{build}'

skip_commits:
  files:
    - '**/*.md'

image: Visual Studio 2017

platform:
  - Win32
  - x64

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

environment:
  VAR_B: value_1

configuration: Release

build_script:
  - cmd: |-
      echo %VAR_A%
      echo %VAR_B%

deploy:
  provider: Webhook
  on:
    message: /\[test-message\]/
  url: https://webhook.site/25526b7b-37b8-4c81-8d6a-910e1f10bf22