version: '{build}'

skip_commits:
  files:
    - '**/*.md'

image: Visual Studio 2017

platform:
  - Win32
  - x64

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

environment:
  VAR_B: value_1
  matrix:
    - VAR_A: value_1
    - VAR_A: value_2

configuration: Release

build_script:
  - cmd: |-
      echo %VAR_A%
      echo %VAR_B%

for:
  -
    matrix:
      only:
        - platform: Win32
        - VAR_A: value_1
      
    environment:
      VAR_B: value_2

  -
    matrix:
      only:
        - platform: x64
        - VAR_A: value_1

    environment:
      VAR_B: value_3